[workspace]

resolver = "2"

members= [
  "core",
  "lib",
  "storage",
  "zome",
]

[workspace.dependencies]
hdi = "0.4.0-beta-dev.30"
hdk = "0.3.0-beta-dev.34"
serde = "=1.0.197"
holo_hash = "=0.3.0-beta-dev.25"
holochain_serialized_bytes = "=0.0.53"
holochain_zome_types = { version = "=0.3.0-beta-dev.31", default-features = false }
zome_utils = { git = "https://github.com/ddd-mtl/zome-utils", branch = "hdk-3.0" }
