[package]
name = "hc_zome_dna_auth_resolver_rpc"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2021"

[dependencies]
serde = "*"
holo_hash = "*"
holochain_zome_types = "*"
holochain_serialized_bytes = "*"

[lib]
crate-type = ["lib"]
