[package]
name = "hc_zome_dna_auth_resolver_core"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2021"

[dependencies]
serde = "*"
hdi = "*"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]
